#!/bin/bash

# dkeg 2014
# betterbright for fbcolors

echo -en "\e]P0bebebe"
echo -en "\e]P818222B"
echo -en "\e]P13b0b0b"
echo -en "\e]P9610b0b"
echo -en "\e]P20b3b0b"
echo -en "\e]PA0b610b"
echo -en "\e]P33a2f0b"
echo -en "\e]PB5f4c0b"
echo -en "\e]P40b173b"
echo -en "\e]PC0b2161"
echo -en "\e]P54f334e"
echo -en "\e]PD64307A"
echo -en "\e]P60b614b"
echo -en "\e]PE088a68"
echo -en "\e]P7555555"
echo -en "\e]PF777777"
