#!/bin/bash

# dkeg 2014
# colorbar
#*background:#000000

echo -en "\e]P0000000"
echo -en "\e]P0111111"
echo -en "\e]P100AED9"
echo -en "\e]P200AF4D"
echo -en "\e]P30FCBBC"
echo -en "\e]P4555555"
echo -en "\e]P534B6E5"
echo -en "\e]P653DB3F"
echo -en "\e]P77C5CCB"
echo -en "\e]P8CC092F"
echo -en "\e]P9D80073"
echo -en "\e]PAFF17A3"
echo -en "\e]PBFF535B"
echo -en "\e]PCFF993A"
echo -en "\e]PDFFE81A"
echo -en "\e]PE716800"
echo -en "\e]PFFFFFFF "
