#!/bin/bash

# dkeg 2014
# iron 

# *background: #0f0e0f
# *foreground: #abaeac

echo -en "\e]P00f0e0f"

echo -en "\e]P1252525"
echo -en "\e]P2464646"
echo -en "\e]P3525252"
echo -en "\e]P42a2a2a"
echo -en "\e]P5b9b9b9"
echo -en "\e]P6e3e3e3"
echo -en "\e]P7f7f7f7"
echo -en "\e]P87c7c7c"
echo -en "\e]P9999999"
echo -en "\e]PAa0a0a0"
echo -en "\e]PB8e8e8e"
echo -en "\e]PC333333"
echo -en "\e]PD686868"
echo -en "\e]PE747474"
echo -en "\e]PF5e5e5e"
