#!/bin/bash

# Dkeg's "vintage" for fb-colors #

echo -en "\e]P0170F0D" #background
echo -en "\e]P875A689" #darkgrey
echo -en "\e]P1222333" #darkred
echo -en "\e]P99CAE8F" #red
echo -en "\e]P22E273B" #darkgreen
echo -en "\e]PAA16C68" #green
echo -en "\e]P32E3647" #brown
echo -en "\e]PBB19476" #yellow
echo -en "\e]P4324E54" #darkblue
echo -en "\e]PCB6C39D" #blue
echo -en "\e]P5533748" #darkmagenta
echo -en "\e]PDE3B58C" #magenta
echo -en "\e]P65A635F" #darkcyan
echo -en "\e]PEF2C799" #cyan
echo -en "\e]P7648C75" #lightgrey
echo -en "\e]PFF9D1AA" #white
clear #for background artifacting
