#!/bin/bash
# this is not ready for use yet (DebianJoe 2014_02_21)

sed -e 's/^\*background/echo -en \"\\e]P0/' \
-e 's/^\*color15/echo -en \"\\e]PF/' \
-e 's/^\*color14/echo -en \"\\e]PE/' \
-e 's/^\*color13/echo -en \"\\e]PD/' \
-e 's/^\*color12/echo -en \"\\e]PC/' \
-e 's/^\*color11/echo -en \"\\e]PB/' \
-e 's/^\*color10/echo -en \"\\e]PA/' \
-e 's/^\*color9/echo -en \"\\e]P9/' \
-e 's/^\*color8/echo -en \"\\e]P8/' \
-e 's/^\*color7/echo -en \"\\e]P7/' \
-e 's/^\*color6/echo -en \"\\e]P6/' \
-e 's/^\*color5/echo -en \"\\e]P5/' \
-e 's/^\*color4/echo -en \"\\e]P4/' \
-e 's/^\*color3/echo -en \"\\e]P3/' \
-e 's/^\*color2/echo -en \"\\e]P2/' \
-e 's/^\*color1/echo -en \"\\e]P1/' \
-e '/^\*color0/d' \
-e '/^\*foreground:/d' \
-e '/^!/d' \
-e 's/\: *#//' \
-e 's/^echo.*/&"/' \
-e '1s/^/#!\/bin\/bash/' \
$1
